# INTELLECTUAL PROPERTY DISCLAIMER:
# THE FOLLOWING CODE WAS GENERATED BY CHATGPT FOR THE REQUEST HELPER
# IT IS BY ANY MEAN NEITHER OUR IMPLEMENTATION NOR OUR IDEAS.

import asyncio
import httpx
from typing import Optional


async def request_with_retry(
        method: str,
        url: str,
        json: Optional[dict] = None,
        headers: Optional[dict] = None,
        retries: int = 3,
        delay: float = 2.0,
        timeout: float = 30.0
) -> httpx.Response:
    """
    Generic async HTTP request with retry support.
    """
    async with httpx.AsyncClient(timeout=timeout) as client:
        for attempt in range(1, retries + 1):
            try:
                if method.lower() == "post":
                    response = await client.post(url, json=json, headers=headers)
                elif method.lower() == "get":
                    response = await client.get(url, params=json, headers=headers)
                else:
                    raise ValueError(f"Unsupported HTTP method: {method}")

                response.raise_for_status()  # raise for 4xx/5xx
                return response

            except (httpx.RequestError, httpx.HTTPStatusError, httpx.ReadTimeout) as e:
                if attempt == retries:
                    raise
                print(f"Attempt {attempt} for {url} failed: {e}. Retrying in {delay}s...")
                await asyncio.sleep(delay)
